name: App-Consumer-Docker-Build-Push

env:  
  ContainerRegistryName: acr${{ vars.NAME}}${{ vars.SUFFIX}}.azurecr.io        
  ImageName: consumer-app:1.0.0.${GITHUB_RUN_NUMBER}

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]  

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-package:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # - name: 'Az CLI login'
    #   uses: azure/login@v1
    #   with:
    #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'      
      run: |          
          echo "ContainerRegistryName: ${{ env.ContainerRegistryName }}"          
          echo "ImageName: ${{ env.ImageName }}"
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: |
    #       az acr login --name ${{ env.ContainerRegistryName }}
    #       docker build . --file cmd/consumer/dockerfile --tag "${{ env.CONTAINER_REGISTRY_NAME }}/$ImageName" 
      
